name: Build

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build Site
        run: npm run build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist
          
